// Systemd unit file generation for native app resources.
//
// Native apps (Zentinel, Stalwart, Kanidm, Tuwunel, mistral.rs, …) run directly
// under systemd instead of inside a Podman container.
//
// Generated files per instance:
//   {name}.service   — the main service unit
//   {name}.socket    — socket activation unit (only when service.socket_ports is set)
//
// Output location: ~/.config/systemd/user/{name}.service
//                  ~/.config/systemd/user/{name}.socket

use anyhow::Result;
use fs_node_core::state::desired::ServiceInstance;

/// Generate a systemd .service unit for a native app instance.
pub fn generate_service(instance: &ServiceInstance) -> Result<String> {
    let s = instance
        .class
        .service
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("{}: no [service] block found", instance.name))?;

    let mut out = String::new();

    out.push_str("# Generated by fsn – do not edit manually\n");
    out.push_str(&format!("# Resource: {}\n\n", instance.class_key));

    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=FreeSynergy.Node – {}\n",
        instance.name
    ));
    out.push_str("After=network-online.target\n");
    out.push_str("Wants=network-online.target\n");

    // If socket activation is used, the socket unit starts this service
    if !s.socket_ports.is_empty() {
        out.push_str(&format!("Requires={}.socket\n", instance.name));
        out.push_str(&format!("After={}.socket\n", instance.name));
    }

    out.push('\n');
    out.push_str("[Service]\n");
    out.push_str("Type=notify\n");

    // Build ExecStart: binary + args (already Jinja2-resolved by the deploy engine)
    let args = instance.resolved_args.join(" ");
    if args.is_empty() {
        out.push_str(&format!("ExecStart={}\n", s.binary));
    } else {
        out.push_str(&format!("ExecStart={} {}\n", s.binary, args));
    }

    if let Some(user) = &s.user {
        out.push_str(&format!("User={}\n", user));
    }
    if let Some(group) = &s.group {
        out.push_str(&format!("Group={}\n", group));
    }

    // Environment file (resolved by deploy engine alongside .service)
    out.push_str(&format!(
        "EnvironmentFile=-/etc/fsn/{}.env\n",
        instance.name
    ));

    out.push_str("Restart=on-failure\n");
    out.push_str("RestartSec=5s\n");

    // Hardening
    out.push_str("NoNewPrivileges=true\n");
    out.push_str("ProtectSystem=strict\n");
    out.push_str("PrivateTmp=true\n");

    out.push('\n');
    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    Ok(out)
}

/// Generate a systemd .socket unit for socket-activated native apps.
///
/// Required for services that need to bind privileged ports (< 1024)
/// without `setcap`. Systemd binds the ports and passes the fds to the service.
pub fn generate_socket(instance: &ServiceInstance) -> Result<Option<String>> {
    let s = instance
        .class
        .service
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("{}: no [service] block found", instance.name))?;

    if s.socket_ports.is_empty() {
        return Ok(None);
    }

    let mut out = String::new();

    out.push_str("# Generated by fsn – do not edit manually\n");
    out.push_str(&format!(
        "# Resource: {} (socket activation)\n\n",
        instance.class_key
    ));

    out.push_str("[Unit]\n");
    out.push_str(&format!(
        "Description=FreeSynergy.Node – {} socket\n",
        instance.name
    ));
    out.push_str(&format!("PartOf={}.service\n\n", instance.name));

    out.push_str("[Socket]\n");
    for port in &s.socket_ports {
        out.push_str(&format!("ListenStream={}\n", port));
    }
    out.push_str("BindIPv6Only=both\n\n");

    out.push_str("[Install]\n");
    out.push_str("WantedBy=sockets.target\n");

    Ok(Some(out))
}

/// Return the systemd .service unit path for a native app instance.
pub fn service_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/systemd/user/{}.service",
        home, instance_name
    ))
}

/// Return the systemd .socket unit path for a native app instance.
pub fn socket_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/systemd/user/{}.socket",
        home, instance_name
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use fs_node_core::{
        config::{
            Constraints, NativeServiceDef, ServiceClass, ServiceContract, ServiceLoad, ServiceMeta,
            ServiceSetup, ServiceType,
        },
        state::desired::ServiceInstance,
    };
    use indexmap::IndexMap;
    use std::collections::HashMap;

    fn make_native_instance(name: &str, ports: Vec<u16>) -> ServiceInstance {
        ServiceInstance {
            name: name.to_string(),
            class_key: format!("apps/{name}"),
            class: ServiceClass {
                meta: ServiceMeta {
                    name: name.to_string(),
                    alias: vec![],
                    service_types: vec![ServiceType::Proxy],
                    author: None,
                    version: "1.0".to_string(),
                    tags: vec![],
                    description: None,
                    website: None,
                    repository: None,
                    port: 443,
                    constraints: Constraints::default(),
                    federation: None,
                    health_path: Some("/".to_string()),
                    health_port: None,
                    health_scheme: None,
                    capabilities: vec![],
                    roles: Default::default(),
                    ui: Default::default(),
                },
                vars: IndexMap::default(),
                load: ServiceLoad::default(),
                container: None,
                service: Some(NativeServiceDef {
                    binary: "/usr/local/bin/zentinel".to_string(),
                    args: vec!["--config".to_string(), "/data/zentinel.kdl".to_string()],
                    user: Some("zentinel".to_string()),
                    group: Some("zentinel".to_string()),
                    socket_ports: ports,
                    healthcheck: None,
                }),
                environment: IndexMap::default(),
                setup: ServiceSetup::default(),
                contract: ServiceContract::default(),
                manifest: None,
                variables: vec![],
                lifecycle: Default::default(),
            },
            service_types: vec![ServiceType::Proxy],
            resolved_env: HashMap::new(),
            resolved_args: vec!["--config".to_string(), "/data/zentinel.kdl".to_string()],
            service_domain: format!("{name}.example.com"),
            alias_domains: vec![],
            sub_services: vec![],
            version: "1.0".to_string(),
            resolved_volumes: vec![],
            capabilities: vec![],
        }
    }

    #[test]
    fn service_unit_contains_unit_section() {
        let inst = make_native_instance("zentinel", vec![]);
        let out = generate_service(&inst).unwrap();
        assert!(out.contains("[Unit]"));
        assert!(out.contains("Description=FreeSynergy.Node – zentinel"));
        assert!(out.contains("After=network-online.target"));
    }

    #[test]
    fn service_unit_contains_execstart() {
        let inst = make_native_instance("zentinel", vec![]);
        let out = generate_service(&inst).unwrap();
        assert!(out.contains("ExecStart=/usr/local/bin/zentinel --config /data/zentinel.kdl"));
    }

    #[test]
    fn service_unit_contains_user() {
        let inst = make_native_instance("zentinel", vec![]);
        let out = generate_service(&inst).unwrap();
        assert!(out.contains("User=zentinel"));
        assert!(out.contains("Group=zentinel"));
    }

    #[test]
    fn service_unit_references_socket_when_ports_set() {
        let inst = make_native_instance("zentinel", vec![80, 443]);
        let out = generate_service(&inst).unwrap();
        assert!(out.contains("Requires=zentinel.socket"));
        assert!(out.contains("After=zentinel.socket"));
    }

    #[test]
    fn socket_unit_generated_for_privileged_ports() {
        let inst = make_native_instance("zentinel", vec![80, 443]);
        let out = generate_socket(&inst).unwrap().unwrap();
        assert!(out.contains("[Socket]"));
        assert!(out.contains("ListenStream=80"));
        assert!(out.contains("ListenStream=443"));
        assert!(out.contains("WantedBy=sockets.target"));
    }

    #[test]
    fn no_socket_unit_when_no_ports() {
        let inst = make_native_instance("stalwart", vec![]);
        let result = generate_socket(&inst).unwrap();
        assert!(result.is_none());
    }
}
