// Environment file generation.
// Replaces playbooks/templates/container.env.j2
//
// Output: ~/.config/containers/systemd/{name}.env

use anyhow::Result;
use fsn_core::state::desired::ServiceInstance;

/// Generate the .env file content for the given module instance.
/// All Jinja2 vars are already resolved in instance.resolved_env.
pub fn generate(instance: &ServiceInstance) -> Result<String> {
    let mut out = String::new();
    out.push_str(&format!("# Generated by fsn – {}\n", instance.class_key));
    out.push_str("# Do not edit manually – regenerated on every deploy\n\n");

    for (key, value) in &instance.resolved_env {
        out.push_str(&format!("{}={}\n", key, value));
    }

    Ok(out)
}

/// Return the canonical env file path for the given instance name.
pub fn env_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.env",
        home, instance_name
    ))
}
