// Quadlet unit file generation.
// Replaces playbooks/templates/container.quadlet.j2 + generate-quadlet.yml
//
// Output: ~/.config/containers/systemd/{name}.container
// (Podman Quadlet format, picked up by systemd after daemon-reload)

use anyhow::Result;
use fsn_core::state::desired::ModuleInstance;

/// Generate a Podman Quadlet .container unit file for the given instance.
pub fn generate(instance: &ModuleInstance) -> Result<String> {
    let c = &instance.class.container;
    let mut out = String::new();

    out.push_str("# Generated by fsn – do not edit manually\n");
    out.push_str(&format!("# Module: {}\n\n", instance.class_key));

    out.push_str("[Unit]\n");
    out.push_str(&format!("Description=FreeSynergy.Node – {}\n", instance.name));
    out.push_str("After=network-online.target\n");
    out.push_str("Wants=network-online.target\n\n");

    out.push_str("[Container]\n");
    out.push_str(&format!("ContainerName={}\n", instance.name));
    out.push_str(&format!("Image={}:{}\n", c.image, c.image_tag));

    // Environment file (always alongside the .container file)
    out.push_str(&format!("EnvironmentFile=%h/.config/containers/systemd/{}.env\n", instance.name));

    for network in &c.networks {
        out.push_str(&format!("Network={}\n", network));
    }

    for volume in &c.volumes {
        out.push_str(&format!("Volume={}\n", volume));
    }

    for port in &c.published_ports {
        out.push_str(&format!("PublishPort={}\n", port));
    }

    if c.read_only {
        out.push_str("ReadOnly=true\n");
    }

    for tmpfs in &c.tmpfs {
        out.push_str(&format!("Tmpfs={}\n", tmpfs));
    }

    for opt in &c.security_opt {
        out.push_str(&format!("SecurityLabelDisable={}\n", opt));
    }

    if let Some(hc) = &c.healthcheck {
        out.push_str(&format!("HealthCmd={}\n", hc.cmd));
        out.push_str(&format!("HealthInterval={}\n", hc.interval));
        out.push_str(&format!("HealthTimeout={}\n", hc.timeout));
        out.push_str(&format!("HealthRetries={}\n", hc.retries));
        out.push_str(&format!("HealthStartPeriod={}\n", hc.start_period));
    }

    out.push('\n');
    out.push_str("[Service]\n");
    out.push_str("Restart=on-failure\n");
    out.push_str("RestartSec=5s\n\n");

    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");

    Ok(out)
}

/// Return the canonical Quadlet file path for the given user and instance name.
pub fn quadlet_path(instance_name: &str) -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(format!(
        "{}/.config/containers/systemd/{}.container",
        home, instance_name
    ))
}
