// Module class definition – maps to modules/{type}/{name}/{name}.toml
//
// Field order in YAML (MANDATORY per RULES.md):
//   module → vars → load → container → environment

use indexmap::IndexMap;
use serde::{Deserialize, Serialize};
use toml::Value;

/// A module class definition (the template/blueprint for a service).
/// Loaded from modules/{type}/{name}/{name}.yml.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleClass {
    pub module: ModuleMeta,

    #[serde(default)]
    pub vars: IndexMap<String, Value>,

    #[serde(default)]
    pub load: ModuleLoad,

    pub container: ContainerDef,

    #[serde(default)]
    pub environment: IndexMap<String, String>,
}

/// Core metadata declared under the `module:` key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleMeta {
    pub name: String,

    #[serde(default)]
    pub alias: Vec<String>,

    #[serde(rename = "type")]
    pub module_type: String,

    pub author: Option<String>,
    pub version: String,

    #[serde(default)]
    pub tags: Vec<String>,

    pub description: Option<String>,
    pub website: Option<String>,
    pub repository: Option<String>,

    /// Primary internal port the service listens on.
    pub port: u16,

    #[serde(default)]
    pub constraints: Constraints,

    pub federation: Option<FederationMeta>,

    /// Path used by Zentinel for upstream health checks.
    pub health_path: Option<String>,
    pub health_port: Option<u16>,
    pub health_scheme: Option<String>,
}

/// Deployment constraints declared per module class.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Constraints {
    /// Maximum number of instances of this module class per host (null = unlimited).
    pub per_host: Option<u32>,

    /// Maximum number of instances of this module class per IP (null = unlimited).
    pub per_ip: Option<u32>,

    /// Locality constraint – if Some(SameHost), must run on same host as consumer.
    pub locality: Option<Locality>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Locality {
    SameHost,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FederationMeta {
    pub enabled: bool,
    pub min_trust: u8,
}

/// Sub-module and service references declared under `load:`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModuleLoad {
    /// Sub-modules this module owns and creates (e.g. postgres, dragonfly).
    #[serde(default)]
    pub modules: IndexMap<String, SubModuleRef>,

    /// Other services whose config this module reads (no ownership).
    #[serde(default)]
    pub services: IndexMap<String, ServiceRef>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubModuleRef {
    pub module_class: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ServiceRef {}

/// Container definition – maps to the `container:` block.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContainerDef {
    pub name: String,
    pub image: String,
    pub image_tag: String,

    /// Auto-generated by engine – NEVER set manually in module YAML.
    #[serde(default)]
    pub networks: Vec<String>,

    #[serde(default)]
    pub volumes: Vec<String>,

    /// Forbidden on all modules except proxy/zentinel.
    #[serde(default)]
    pub published_ports: Vec<String>,

    pub healthcheck: Option<HealthCheck>,

    #[serde(default)]
    pub read_only: bool,

    #[serde(default)]
    pub tmpfs: Vec<String>,

    #[serde(default)]
    pub security_opt: Vec<String>,

    #[serde(default)]
    pub ulimits: IndexMap<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthCheck {
    pub cmd: String,
    pub interval: String,
    pub timeout: String,
    pub retries: u32,
    pub start_period: String,
}
